data:
  raw: "data/raw"
  processed: "data/processed"
  clip_polygons: "data/polygons/biome_polygons.gpkg"
  class_polygons: "data/polygons/classification_polygons.gpkg"

export:
  save_intermediate: true
  intermediate_path: "data/intermediate"

biomes:
  urban: "Урбанизированные территории"
  forest: "Лесные массивы"
  agriculture: "Сельскохозяйственные угодья"

landsat:
  ms_bands: [2, 3, 4, 5, 6, 7]  # B2-B7
  pan_band: 8                   # B8

